const wordsDB = {
    'Animales': [
        { normal: "Perro", distraido: "Lobo" },
        { normal: "Gato", distraido: "Lince" },
        { normal: "León", distraido: "Tigre" },
        { normal: "Tigre", distraido: "Leopardo" },
        { normal: "Elefante", distraido: "Rinoceronte" },
        { normal: "Jirafa", distraido: "Okapi" },
        { normal: "Cebra", distraido: "Caballo" },
        { normal: "Oso", distraido: "Panda" },
        { normal: "Zorro", distraido: "Coyote" },
        { normal: "Lobo", distraido: "Perro" },
        { normal: "Ciervo", distraido: "Alce" },
        { normal: "Vaca", distraido: "Toro" },
        { normal: "Caballo", distraido: "Poni" },
        { normal: "Cerdo", distraido: "Jabalí" },
        { normal: "Oveja", distraido: "Cabra" },
        { normal: "Gallina", distraido: "Gallo" },
        { normal: "Gato montés", distraido: "Puma" },
        { normal: "Conejo", distraido: "Liebre" },
        { normal: "Ardilla", distraido: "Hámster" },
        { normal: "Ratón", distraido: "Rata" },
        { normal: "Camello", distraido: "Dromedario" },
        { normal: "Dromedario", distraido: "Llama" },
        { normal: "Rinoceronte", distraido: "Hipopótamo" },
        { normal: "Hipopótamo", distraido: "Manatí" },
        { normal: "Koala", distraido: "Perezoso" },
        { normal: "Canguro", distraido: "Wallaby" },
        { normal: "Panda", distraido: "Oso Hormiguero" },
        { normal: "Mono", distraido: "Chimpancé" },
        { normal: "Chimpancé", distraido: "Orangután" },
        { normal: "Gorila", distraido: "Mandril" },
        { normal: "Pingüino", distraido: "Pato" },
        { normal: "Foca", distraido: "Morsa" },
        { normal: "Delfín", distraido: "Marsopa" },
        { normal: "Ballena", distraido: "Cachalote" },
        { normal: "Tiburón", distraido: "Barracuda" },
        { normal: "Tortuga", distraido: "Galápago" },
        { normal: "Cocodrilo", distraido: "Caimán" },
        { normal: "Serpiente", distraido: "Culebra" },
        { normal: "Loro", distraido: "Guacamayo" },
        { normal: "Colibrí", distraido: "Picaflor" },
        { normal: "Águila", distraido: "Halcón" },
        { normal: "Halcón", distraido: "Búho" },
        { normal: "Paloma", distraido: "Tórtola" },
        { normal: "Cuervo", distraido: "Urraca" },
        { normal: "Hormiga", distraido: "Termita" },
        { normal: "Abeja", distraido: "Avispa" },
        { normal: "Mariposa", distraido: "Polilla" },
        { normal: "Mosca", distraido: "Tábano" },
        { normal: "Mosquito", distraido: "Zancudo" },
        { normal: "Araña", distraido: "Tarántula" },
        { normal: "Grillo", distraido: "Saltamontes" },
        { normal: "Escorpión", distraido: "Alacrán" },
        { normal: "Caracol", distraido: "Babosa" },
        { normal: "Gusano", distraido: "Lombriz" },
        { normal: "Medusa", distraido: "Anémona" },
        { normal: "Pulpo", distraido: "Calamar" },
        { normal: "Calamar", distraido: "Nautilo" },
        { normal: "Erizo de mar", distraido: "Estrella de mar" },
        { normal: "Estrella de mar", distraido: "Sol de mar" },
        { normal: "Coral", distraido: "Arrecife" },
        { normal: "Mantarraya", distraido: "Raya eléctrica" },
        { normal: "Pez dorado", distraido: "Carpa Koi" },
        { normal: "Pez payaso", distraido: "Pez cirujano" },
        { normal: "Salmón", distraido: "Trucha" },
        { normal: "Trucha", distraido: "Sardina" },
        { normal: "Bacalao", distraido: "Mero" },
        { normal: "Atún", distraido: "Bonito" },
        { normal: "Pollo", distraido: "Pavo" },
        { normal: "Tucán", distraido: "Cacatúa" },
        { normal: "Cisne", distraido: "Ganso" },
        { normal: "Flamenco", distraido: "Garza" },
        { normal: "Pato", distraido: "Oca" },
        { normal: "Pavo", distraido: "Faisán" },
        { normal: "Búfalo", distraido: "Bisonte" },
        { normal: "Alce", distraido: "Reno" },
        { normal: "Reno", distraido: "Caribú" },
        { normal: "Búho", distraido: "Lechuza" },
        { normal: "Fénix", distraido: "Dragón" },
        { normal: "Unicornio", distraido: "Pegaso" },
        { normal: "Dragón", distraido: "Wyvern" },
        { normal: "Grifo", distraido: "Hipogrifo" },
        { normal: "Centauro", distraido: "Minotauro" },
        { normal: "Sirena", distraido: "Ninfa" },
        { normal: "Yeti", distraido: "Bigfoot" },
        { normal: "Gnomo", distraido: "Duende" },
        { normal: "Hada", distraido: "Elfo" },
        { normal: "Duende", distraido: "Trasgo" },
        { normal: "Mago", distraido: "Hechicero" },
        { normal: "Bruja", distraido: "Chamán" },
        { normal: "Vampiro", distraido: "Hombre lobo" },
        { normal: "Hombre lobo", distraido: "Licántropo" }
    ],
    'Cine': [
        { normal: { title: "Gone with the Wind", translation: "(Lo que el viento se llevó) (1939)" }, distraido: { title: "Casablanca", translation: "(1942)" } },
        { normal: { title: "Avatar", translation: "(2009)" }, distraido: { title: "Dune", translation: "(2021)" } },
        { normal: { title: "Titanic", translation: "(1997)" }, distraido: { title: "La Aventura del Poseidón", translation: "(1972)" } },
        { normal: { title: "Star Wars", translation: "(Guerra de las Galaxias) (1977)" }, distraido: { title: "Star Trek", translation: "(2009)" } },
        { normal: { title: "The Avengers", translation: "(Los Vengadores) (2019)" }, distraido: { title: "La Liga de la Justicia", translation: "(2017)" } },
        { normal: { title: "E.T. the Extra-Terrestrial", translation: "(E.T., el Extraterrestre) (1982)" }, distraido: { title: "Mi Amigo Mac", translation: "(1988)" } },
        { normal: { title: "The Little Mermaid", translation: "(La sirenita) (2023)" }, distraido: { title: "Moana", translation: "(2016)" } },
        { normal: { title: "Jurassic Park", translation: "(Parque Jurásico) (1993)" }, distraido: { title: "Godzilla", translation: "(1998)" } },
        { normal: { title: "Zathura: A Space Adventure", translation: "(Zatura: Una aventura espacial) (2005)" }, distraido: { title: "Jumanji", translation: "(1995)" } },
        { normal: { title: "The Exorcist", translation: "(El exorcista) (1973)" }, distraido: { title: "El Conjuro", translation: "(2013)" } },
        { normal: { title: "Snow White and the Seven Dwarfs", translation: "(Blancanieves y los siete enanitos) (1937)" }, distraido: { title: "Cenicienta", translation: "(1950)" } },
        { normal: { title: "One Hundred and One Dalmatians", translation: "(101 Dálmatas) (1961)" }, distraido: { title: "La Dama y el Vagabundo", translation: "(1955)" } },
        { normal: { title: "The Lion King", translation: "(El rey león) (1994)" }, distraido: { title: "El Libro de la Selva", translation: "(1967)" } },
        { normal: { title: "Indiana Jones", translation: "(1981)" }, distraido: { title: "Tomb Raider", translation: "(2001)" } },
        { normal: { title: "Jaws", translation: "(Tiburón) (1975)" }, distraido: { title: "Piraña", translation: "(1978)" } },
        { normal: { title: "The Godfather", translation: "(El Padrino) (1972)" }, distraido: { title: "Caracortada", translation: "(1983)" } },
        { normal: { title: "Forrest Gump", translation: "(1994)" }, distraido: { title: "El Curioso Caso de Benjamin Button", translation: "(2008)" } },
        { normal: { title: "Black Panther", translation: "(Pantera Negra) (2018)" }, distraido: { title: "Blade", translation: "(1998)" } },
        { normal: { title: "Spider-Man: No Way Home", translation: "(Spider-Man: Sin camino a casa) (2021)" }, distraido: { title: "The Flash", translation: "(2023)" } },
        { normal: { title: "The Lord of the Rings: The Return of the King", translation: "(El Señor de los Anillos: El retorno del Rey) (2003)" }, distraido: { title: "Las Crónicas de Narnia", translation: "(2005)" } },
        { normal: { title: "The Dark Knight", translation: "(Batman: El caballero de la noche) (2008)" }, distraido: { title: "El Guasón (Joker)", translation: "(2019)" } },
        { normal: { title: "The Hobbit: An Unexpected Journey", translation: "(El Hobbit: Un viaje inesperado) (2012)" }, distraido: { title: "Willow", translation: "(1988)" } },
        { normal: { title: "Beauty and the Beast", translation: "(La bella y la bestia) (2017)" }, distraido: { title: "Aladdín", translation: "(2019)" } },
        { normal: { title: "Toy Story 3", translation: "(2010)" }, distraido: { title: "Bichos: Una Aventura en Miniatura", translation: "(1998)" } },
        { normal: { title: "Pirates of the Caribbean: Dead Man's Chest", translation: "(Piratas del Caribe: El cofre de la muerte) (2006)" }, distraido: { title: "La Isla del Tesoro", translation: "(1950)" } },
        { normal: { title: "Frozen", translation: "(2013)" }, distraido: { title: "Enredados", translation: "(2010)" } },
        { normal: { title: "Furious 7", translation: "(Rápidos y Furiosos 7) (2015)" }, distraido: { title: "Need for Speed", translation: "(2014)" } },
        { normal: { title: "A Beautiful Mind", translation: "(Una Mente Brillante) (2001)" }, distraido: { title: "La Teoría del Todo", translation: "(2014)" } },
        { normal: { title: "Dead Poets Society", translation: "(La sociedad de los poetas muertos) (1989)" }, distraido: { title: "La Sonrisa de Mona Lisa", translation: "(2003)" } },
        { normal: { title: "The Guilty", translation: "(El culpable) (2021)" }, distraido: { title: "El Silencio de los Inocentes", translation: "(1991)" } },
        { normal: { title: "The Queen's Gambit", translation: "(Gambito de dama) (2020)" }, distraido: { title: "En Busca de Bobby Fischer", translation: "(1993)" } },
        { normal: { title: "Blade Runner 2049", translation: "(2017)" }, distraido: { title: "Dune", translation: "(2021)" } },
        { normal: { title: "Fifty Shades of Grey", translation: "(50 sombras de Grey) (2015)" }, distraido: { title: "365 Días", translation: "(2020)" } },
        { normal: { title: "Her", translation: "(Ella) (2013)" }, distraido: { title: "Ex Machina", translation: "(2014)" } },
        { normal: { title: "Whiplash", translation: "(Música y obsesión) (2014)" }, distraido: { title: "La La Land", translation: "(2016)" } },
        { normal: { title: "The Wolf of Wall Street", translation: "(El lobo de Wall Street) (2013)" }, distraido: { title: "La Gran Estafa", translation: "(2001)" } },
        { normal: { title: "About Time", translation: "(Cuestión de tiempo) (2013)" }, distraido: { title: "Te Amaré por Siempre", translation: "(2009)" } },
        { normal: { title: "Django Unchained", translation: "(Django sin cadenas) (2012)" }, distraido: { title: "Los 8 Más Odiados", translation: "(2015)" } },
        { normal: { title: "Project X", translation: "(Proyecto X) (2012)" }, distraido: { title: "Supercool", translation: "(2007)" } },
        { normal: { title: "Drive", translation: "(El escape) (2011)" }, distraido: { title: "Baby Driver", translation: "(2017)" } },
        { normal: { title: "127 Hours", translation: "(127 horas) (2010)" }, distraido: { title: "Náufrago", translation: "(2000)" } },
        { normal: { title: "Chinese Takeaway", translation: "(Un cuento chino) (2011)" }, distraido: { title: "El Secreto de sus Ojos", translation: "(2009)" } }
    ],
    'Colores': [
        { normal: "rojo", distraido: "granate" },
        { normal: "amarillo", distraido: "dorado" },
        { normal: "marron", distraido: "beige" },
        { normal: "verde", distraido: "esmeralda" },
        { normal: "azul", distraido: "turquesa" },
        { normal: "celeste", distraido: "cian" },
        { normal: "turquesa", distraido: "aguamarina" },
        { normal: "lavanda", distraido: "lila" },
        { normal: "violeta", distraido: "púrpura" },
        { normal: "rosa", distraido: "fucsia" },
        { normal: "blanco", distraido: "marfil" },
        { normal: "gris", distraido: "plata" },
        { normal: "negro", distraido: "carbón" },
        { normal: "naranja", distraido: "mandarina" },
        { normal: "beige", distraido: "crema" }
    ],
    'Comida': [
        { normal: "Asado", distraido: "Parrillada" },
        { normal: "Milanesa", distraido: "Escalope" },
        { normal: "Empanadas", distraido: "Canastitas" },
        { normal: "Locro", distraido: "Guiso" },
        { normal: "Humita", distraido: "Tamal" },
        { normal: "Choripán", distraido: "Pancho" },
        { normal: "Provoleta", distraido: "Queso a la parrilla" },
        { normal: "Carbonada", distraido: "Cazuela" },
        { normal: "Parrillada", distraido: "Barbacoa" },
        { normal: "Matambre a la pizza", distraido: "Carne a la pizza" },
        { normal: "Bife de chorizo", distraido: "Entrecot" },
        { normal: "Vacio", distraido: "Falda" },
        { normal: "Chinchulines", distraido: "Tripas" },
        { normal: "Mollejas", distraido: "Entraña" },
        { normal: "Salamin", distraido: "Longaniza" },
        { normal: "Guiso de lentejas", distraido: "Fabada" },
        { normal: "Pastel de papas", distraido: "Pastel de carne" },
        { normal: "Tallarines", distraido: "Fideos" },
        { normal: "Ñoquis", distraido: "Ravioles" },
        { normal: "Polenta", distraido: "Sémola" },
        { normal: "Pizza", distraido: "Focaccia" },
        { normal: "Tortilla", distraido: "Omelette" },
        { normal: "Rabas", distraido: "Calamares fritos" },
        { normal: "Sándwich", distraido: "Bocadillo" },
        { normal: "Hamburguesa", distraido: "Albóndiga" },
        { normal: "Milanesa a la napolitana", distraido: "Pollo a la parmesana" },
        { normal: "Morcilla", distraido: "Butifarra" },
        { normal: "Salchicha", distraido: "Viena" },
        { normal: "Pescado", distraido: "Marisco" },
        { normal: "Tarta de jamón y queso", distraido: "Quiche" },
        { normal: "Paella", distraido: "Arroz con mariscos" },
        { normal: "Choclo", distraido: "Maíz" },
        { normal: "Ensalada", distraido: "Verduras" },
        { normal: "Sopa", distraido: "Caldo" },
        { normal: "Caldo", distraido: "Consomé" },
        { normal: "Puchero", distraido: "Cocido" },
        { normal: "Flan", distraido: "Pudín" },
        { normal: "Panqueques con dulce de leche", distraido: "Crepes con cajeta" },
        { normal: "Alfajores de maicena", distraido: "Galletitas de maicena" },
        { normal: "Alfajore", distraido: "Galleta" },
        { normal: "Budín de pan", distraido: "Torta de pan" },
        { normal: "Torta", distraido: "Pastel" },
        { normal: "Cheesecake", distraido: "Tarta de queso" },
        { normal: "Chocotorta", distraido: "Torta de galletitas" },
        { normal: "Selva Negra", distraido: "Torta de chocolate y cereza" },
        { normal: "Helado de dulce de leche", distraido: "Helado de cajeta" },
        { normal: "Helado de menta granizada", distraido: "Helado de menta con chocolate" },
        { normal: "Tiramisú", distraido: "Postre de café" },
        { normal: "Duraznos en almíbar", distraido: "Melocotones en conserva" },
        { normal: "Ensalada de frutas", distraido: "Macedonia" },
        { normal: "Frutillas con crema", distraido: "Fresas con nata" },
        { normal: "Mousse de chocolate", distraido: "Espuma de chocolate" },
        { normal: "Mousse de limón", distraido: "Crema de limón" },
        { normal: "Brownie con helado", distraido: "Pastel de chocolate con helado" },
        { normal: "Banana", distraido: "Plátano" }
    ],
    'Deportes': [
        { normal: "Fútbol", distraido: "Rugby" },
        { normal: "Baloncesto", distraido: "Voleibol" },
        { normal: "Béisbol", distraido: "Críquet" },
        { normal: "Tenis", distraido: "Pádel" },
        { normal: "Golf", distraido: "Mini-golf" },
        { normal: "Natación", distraido: "Waterpolo" },
        { normal: "Atletismo", distraido: "Gimnasia" },
        { normal: "Boxeo", distraido: "Kickboxing" },
        { normal: "Voleibol", distraido: "Balonmano" },
        { normal: "Rugby", distraido: "Fútbol Americano" },
        { normal: "Fútbol americano", distraido: "Fútbol australiano" },
        { normal: "Hockey sobre hielo", distraido: "Patinaje sobre hielo" },
        { normal: "Automovilismo", distraido: "Motociclismo" },
        { normal: "Motociclismo", distraido: "Karting" },
        { normal: "Ciclismo", distraido: "BMX" },
        { normal: "Esgrima", distraido: "Kendo" },
        { normal: "Judo", distraido: "Karate" },
        { normal: "Karate", distraido: "Taekwondo" },
        { normal: "Taekwondo", distraido: "Kung Fu" },
        { normal: "Lucha libre", distraido: "Lucha grecorromana" },
        { normal: "Gimnasia", distraido: "Acrobacia" },
        { normal: "Tiro con arco", distraido: "Ballesta" },
        { normal: "Bádminton", distraido: "Tenis de mesa" },
        { normal: "Ping Pong", distraido: "Tenis de mesa" },
        { normal: "Balonmano", distraido: "Netball" },
        { normal: "Polo", distraido: "Equitación" },
        { normal: "Caza", distraido: "Pesca" },
        { normal: "Pesca deportiva", distraido: "Pesca submarina" },
        { normal: "Surf", distraido: "Bodyboard" },
        { normal: "Esquí", distraido: "Snowboard" },
        { normal: "Snowboard", distraido: "Sandboard" },
        { normal: "Patinaje artistico", distraido: "Baile sobre hielo" },
        { normal: "Tiro", distraido: "Tiro al plato" },
        { normal: "Triatlón", distraido: "Decatlón" },
        { normal: "Decatlón", distraido: "Pentatlón" },
        { normal: "Clavado", distraido: "Salto de trampolín" },
        { normal: "Lanzamiento de disco", distraido: "Lanzamiento de martillo" },
        { normal: "Lanzamiento de jabalina", distraido: "Lanzamiento de peso" },
        { normal: "Combinada nórdica", distraido: "Biatlón" },
        { normal: "Hockey sobre césped", distraido: "Floorball" },
        { normal: "Waterpolo", distraido: "Natación sincronizada" },
        { normal: "Fútbol sala", distraido: "Futsal" },
        { normal: "Kickboxing", distraido: "Muay Thai" },
        { normal: "Kendo", distraido: "Iaido" },
        { normal: "Aikido", distraido: "Jiu-jitsu" },
        { normal: "Parkour", distraido: "Freerunning" },
        { normal: "Skateboarding", distraido: "Longboard" },
        { normal: "Escalada", distraido: "Alpinismo" },
        { normal: "Senderismo", distraido: "Trekking" },
        { normal: "Paracaidismo", distraido: "Salto base" },
        { normal: "Buceo", distraido: "Snorkel" },
        { normal: "Remo", distraido: "Canotaje" },
        { normal: "Vela", distraido: "Windsurf" },
        { normal: "Rafting", distraido: "Kayak" },
        { normal: "Wakeboard", distraido: "Esquí acuático" },
        { normal: "Windsurf", distraido: "Kitesurf" },
        { normal: "Kitesurf", distraido: "Surf de vela" },
        { normal: "Críquet", distraido: "Béisbol" },
        { normal: "Lacrosse", distraido: "Intercrosse" }
    ],
    'Lol': [
        { normal: "Sócrates", distraido: "Platón" },
        { normal: "Aristóteles", distraido: "Diógenes" },
        { normal: "Banghó", distraido: "Compaq" },
        { normal: "Cristóbal Colón", distraido: "Américo Vespucio" },
        { normal: "Guille", distraido: "Willy" },
        { normal: "Enzo", distraido: "Renzo" },
        { normal: "Nacho", distraido: "Nito" },
        { normal: "Nahu", distraido: "Nahuel" },
        { normal: "Vale", distraido: "Valeria" },
        { normal: "Mirko", distraido: "Marley" },
        { normal: "Mía", distraido: "Milo" },
        { normal: "Sofi", distraido: "Fifi" },
        { normal: "Coqui", distraido: "Pipo" },
        { normal: "Guardabarros de Falcon", distraido: "Paragolpes de Chevy" },
        { normal: "Cinturón", distraido: "Tirantes" },
        { normal: "Coca-Cola en botella de vidrio", distraido: "Pepsi en lata" },
        { normal: "Queso Cheddar", distraido: "Queso Dambo" },
        { normal: "Monopoly", distraido: "Estanciero" },
        { normal: "Discord", distraido: "Skype" },
        { normal: "Minecraft", distraido: "Roblox" },
        { normal: "Impostor", distraido: "Detective" },
        { normal: "WhatsApp", distraido: "Telegram" },
        { normal: "Gmail", distraido: "Outlook" },
        { normal: "YouTube", distraido: "Vimeo" },
        { normal: "TikTok", distraido: "Instagram Reels" },
        { normal: "Chaqueta", distraido: "Campera" },
        { normal: "Camión", distraido: "Tractor" },
        { normal: "Camaro", distraido: "Mustang" },
        { normal: "Camarón", distraido: "Langostino" },
        { normal: "Batería (eléctrica)", distraido: "Pila" },
        { normal: "Cargador", distraido: "Enchufe" },
        { normal: "Cuernos", distraido: "Antenas" },
        { normal: "Boludo/a", distraido: "Pelotudo/a" },
        { normal: "Culo", distraido: "Trasero" },
        { normal: "Pito", distraido: "Pene" },
        { normal: "Teta", distraido: "Seno" },
        { normal: "Caca", distraido: "Excremento" },
        { normal: "Pis", distraido: "Orina" },
        { normal: "Puto/a", distraido: "Homosexual" },
        { normal: "Milanesa de pollo", distraido: "Pechuga a la plancha" },
        { normal: "Sorrentinos de jamon y Queso", distraido: "Ravioles de ricota" },
        { normal: "Nikola Tesla", distraido: "Thomas Edison" },
        { normal: "Random", distraido: "Aleatorio" },
        { normal: "Esto no es una palabra: Tenes que decir 2 palabras", distraido: "Esto no es una palabra: Tenes que decir 3 palabras" },
        { normal: "Esto no es una palabra: Tenes que decir lo contrario a lo que diga la anterior persona", distraido: "Esto no es una palabra: Tenes que decir lo mismo que la anterior persona" },
        { normal: "Insulto", distraido: "Pirope" },
        { normal: "Niño rata", distraido: "Gamer tóxico" }
    ],
    'Lugares': [
        { normal: "Aeropuerto", distraido: "Terminal de autobuses" },
        { normal: "Puerto", distraido: "Muelle" },
        { normal: "Fábrica", distraido: "Taller" },
        { normal: "Granja", distraido: "Estancia" },
        { normal: "Bosque", distraido: "Selva" },
        { normal: "Desierto", distraido: "Sábana" },
        { normal: "Volcán", distraido: "Montaña" },
        { normal: "Cementerio", distraido: "Morgue" },
        { normal: "Estadio", distraido: "Coliseo" },
        { normal: "Cancha de fútbol", distraido: "Cancha de tenis" },
        { normal: "Pista de atletismo", distraido: "Velódromo" },
        { normal: "Piscina", distraido: "Alberca" },
        { normal: "Gimnasio", distraido: "Centro deportivo" },
        { normal: "Cine", distraido: "Teatro" },
        { normal: "Teatro", distraido: "Anfiteatro" },
        { normal: "Biblioteca", distraido: "Librería" },
        { normal: "Museo", distraido: "Galería de arte" },
        { normal: "Galería de arte", distraido: "Exposición" },
        { normal: "Supermercado", distraido: "Mercado" },
        { normal: "Tienda de ropa", distraido: "Boutique" },
        { normal: "Zapatería", distraido: "Tienda de calzado" },
        { normal: "Banco", distraido: "Casa de cambio" },
        { normal: "Correo", distraido: "Oficina postal" },
        { normal: "Comisaría", distraido: "Estación de policía" },
        { normal: "Bomberos", distraido: "Cuartel de bomberos" },
        { normal: "Hotel", distraido: "Hostal" },
        { normal: "Motel", distraido: "Apart-hotel" },
        { normal: "Albergue", distraido: "Posada" },
        { normal: "Cabaña", distraido: "Bungalow" },
        { normal: "Campamento", distraido: "Camping" },
        { normal: "Zoológico", distraido: "Reserva natural" },
        { normal: "Acuario", distraido: "Oceanario" },
        { normal: "Jardín botánico", distraido: "Invernadero" },
        { normal: "Parque de diversiones", distraido: "Feria" },
        { normal: "Parque temático", distraido: "Parque de atracciones" },
        { normal: "Castillo", distraido: "Fortaleza" },
        { normal: "Ruinas", distraido: "Yacimiento arqueológico" },
        { normal: "Cueva", distraido: "Caverna" },
        { normal: "Cañón", distraido: "Garganta" },
        { normal: "Glaciar", distraido: "Nevero" },
        { normal: "Isla", distraido: "Archipiélago" },
        { normal: "Península", distraido: "Cabo" },
        { normal: "Cataratas", distraido: "Cascada" },
        { normal: "Oasis", distraido: "Manantial" },
        { normal: "Pantano", distraido: "Ciénaga" },
        { normal: "Acantilado", distraido: "Precipicio" },
        { normal: "Arrecife de coral", distraido: "Atolón" },
        { normal: "Estación espacial", distraido: "Observatorio" },
        { normal: "Planeta", distraido: "Estrella" },
        { normal: "Galaxia", distraido: "Nebulosa" }
    ],
    'Objetos': [
        { normal: "Botón", distraido: "Interruptor" },
        { normal: "Mesa", distraido: "Escritorio" },
        { normal: "Celular", distraido: "Teléfono fijo" },
        { normal: "Botella", distraido: "Frasco" },
        { normal: "Silla", distraido: "Banqueta" },
        { normal: "Lámpara", distraido: "Foco" },
        { normal: "Televisión", distraido: "Monitor" },
        { normal: "Computadora", distraido: "Laptop" },
        { normal: "Libro", distraido: "Cuaderno" },
        { normal: "Cuaderno", distraido: "Libreta" },
        { normal: "Bolígrafo", distraido: "Lápiz" },
        { normal: "Lápiz", distraido: "Portaminas" },
        { normal: "Mochila", distraido: "Bolso" },
        { normal: "Zapatos", distraido: "Zapatillas" },
        { normal: "Pantalones", distraido: "Jeans" },
        { normal: "Camisa", distraido: "Remera" },
        { normal: "Reloj", distraido: "Cronómetro" },
        { normal: "Vaso", distraido: "Copa" },
        { normal: "Tenedor", distraido: "Trinche" },
        { normal: "Cuchara", distraido: "Cucharón" },
        { normal: "Cuchillo", distraido: "Navaja" },
        { normal: "Plato", distraido: "Bandeja" },
        { normal: "Taza", distraido: "Pocillo" },
        { normal: "Sartén", distraido: "Wok" },
        { normal: "Olla", distraido: "Cacerola" },
        { normal: "Microondas", distraido: "Horno eléctrico" },
        { normal: "Refrigerador", distraido: "Heladera" },
        { normal: "Estufa", distraido: "Calefactor" },
        { normal: "Cama", distraido: "Catrera" },
        { normal: "Almohada", distraido: "Cojín" },
        { normal: "Sábana", distraido: "Frazada" },
        { normal: "Manta", distraido: "Cobertor" },
        { normal: "Espejo", distraido: "Reflejo" },
        { normal: "Cepillo de dientes", distraido: "Hilo dental" },
        { normal: "Jabón", distraido: "Shampoo" },
        { normal: "Champú", distraido: "Acondicionador" },
        { normal: "Toalla", distraido: "Toallón" },
        { normal: "Lavadora", distraido: "Lavarropas" },
        { normal: "Secadora", distraido: "Secarropas" },
        { normal: "Aspiradora", distraido: "Barredora" },
        { normal: "Escoba", distraido: "Cepillo" },
        { normal: "Trapeador", distraido: "Mopa" },
        { normal: "Maceta", distraido: "Jardinera" },
        { normal: "Planta", distraido: "Arbusto" },
        { normal: "Florero", distraido: "Jarrón" },
        { normal: "Tijeras", distraido: "Cizalla" },
        { normal: "Martillo", distraido: "Mazo" },
        { normal: "Destornillador", distraido: "Atornillador" },
        { normal: "Clavo", distraido: "Tornillo" },
        { normal: "Tornillo", distraido: "Tuerca" },
        { normal: "Llave", distraido: "Ganzúa" },
        { normal: "Candado", distraido: "Cerradura" },
        { normal: "Billetera", distraido: "Monedero" },
        { normal: "Monedero", distraido: "Cartera" },
        { normal: "Llaves", distraido: "Tarjeta magnética" },
        { normal: "Coche", distraido: "Automóvil" },
        { normal: "Bicicleta", distraido: "Motocicleta" },
        { normal: "Casco", distraido: "Gorra" },
        { normal: "Guantes", distraido: "Manoplas" },
        { normal: "Sombrero", distraido: "Gorro" },
        { normal: "Bufanda", distraido: "Pañuelo" },
        { normal: "Paraguas", distraido: "Sombrilla" },
        { normal: "Gafas de sol", distraido: "Lentes de sol" },
        { normal: "Anillo", distraido: "Sortija" },
        { normal: "Collar", distraido: "Gargantilla" },
        { normal: "Pulsera", distraido: "Brazalete" },
        { normal: "Anzuelo", distraido: "Señuelo" },
        { normal: "Caña de pescar", distraido: "Red de pescar" },
        { normal: "Pelota", distraido: "Balón" },
        { normal: "Balón", distraido: "Esférico" },
        { normal: "Raqueta", distraido: "Pala" },
        { normal: "Guitarra", distraido: "Bajo" },
        { normal: "Piano", distraido: "Teclado" },
        { normal: "Tambor", distraido: "Bombo" },
        { normal: "Micrófono", distraido: "Altavoz" },
        { normal: "Auriculares", distraido: "Audífonos" },
        { normal: "Altavoz", distraido: "Parlante" },
        { normal: "Batería", distraido: "Pila" },
        { normal: "Linterna", distraido: "Faro" },
        { normal: "Pila", distraido: "Acumulador" },
        { normal: "Cuerda", distraido: "Soga" },
        { normal: "Cinta métrica", distraido: "Regla" },
        { normal: "Mapa", distraido: "Plano" },
        { normal: "Brújula", distraido: "GPS" },
        { normal: "Linterna de cabeza", distraido: "Lámpara de minero" },
        { normal: "Silbato", distraido: "Pito" },
        { normal: "Candelabro", distraido: "Candelero" },
        { normal: "Vela", distraido: "Cirio" },
        { normal: "Fósforos", distraido: "Cerillas" },
        { normal: "Encendedor", distraido: "Mechero" },
        { normal: "Termo", distraido: "Cantimplora" },
        { normal: "Báscula", distraido: "Balanza" },
        { normal: "Mochila de senderismo", distraido: "Mochila de camping" },
        { normal: "Tienda de campaña", distraido: "Carpa" },
        { normal: "Pincel", distraido: "Brocha" },
        { normal: "Pintura", distraido: "Tinte" },
        { normal: "Lienzo", distraido: "Bastidor" },
        { normal: "Tarjeta de crédito", distraido: "Tarjeta de débito" },
        { normal: "Pasaporte", distraido: "Visa" },
        { normal: "Documento de identidad", distraido: "Cédula" },
        { normal: "Carrito de supermercado", distraido: "Cesta de compras" },
        { normal: "Cesto de basura", distraido: "Papelera" },
        { normal: "Dispensador de jabón", distraido: "Jabonera" },
        { normal: "Pomo de puerta", distraido: "Manija" },
        { normal: "Percha", distraido: "Colgador" },
        { normal: "Cinta adhesiva", distraido: "Pegamento" },
        { normal: "Bolso", distraido: "Maletín" },
        { normal: "Bolsa", distraido: "Saco" },
        { normal: "Cartera de mano", distraido: "Clutch" },
        { normal: "Cinturón", distraido: "Faja" },
        { normal: "Cordón de zapato", distraido: "Agujeta" },
        { normal: "Zapatilla", distraido: "Tenis" },
        { normal: "Botín", distraido: "Bota" },
        { normal: "Gorra", distraido: "Visera" },
        { normal: "Calcetín", distraido: "Media" },
        { normal: "Panty", distraido: "Leotardo" },
        { normal: "Paraguas de playa", distraido: "Quitasol" },
        { normal: "Tumbona", distraido: "Reposera" },
        { normal: "Sombrilla", distraido: "Parasol" },
        { normal: "Pelota de playa", distraido: "Balón de playa" },
        { normal: "Flotador", distraido: "Salvavidas" },
        { normal: "Chanclas", distraido: "Sandalias" },
        { normal: "Gafas de natación", distraido: "Antiparras" },
        { normal: "Gorro de natación", distraido: "Gorra de baño" },
        { normal: "Tabla de surf", distraido: "Bodyboard" },
        { normal: "Patineta", distraido: "Skateboard" },
        { normal: "Patines", distraido: "Rollers" },
        { normal: "Scooter", distraido: "Monopatín" },
        { normal: "Motocicleta", distraido: "Moto" },
        { normal: "Autobús", distraido: "Colectivo" },
        { normal: "Tren", distraido: "Ferrocarril" },
        { normal: "Avión", distraido: "Aeroplano" },
        { normal: "Barco", distraido: "Buque" },
        { normal: "Remo", distraido: "Pala" },
        { normal: "Vela de barco", distraido: "Mástil" },
        { normal: "GPS", distraido: "Navegador" },
        { normal: "Linterna de mano", distraido: "Antorcha" },
        { normal: "Cuchillo de bolsillo", distraido: "Cortaplumas" },
        { normal: "Navaja suiza", distraido: "Multiherramienta" },
        { normal: "Soga", distraido: "Lazo" },
        { normal: "Mosquetón", distraido: "Gancho" },
        { normal: "Saco de dormir", distraido: "Bolsa de dormir" },
        { normal: "Colchoneta", distraido: "Esterilla" },
        { normal: "Hornillo", distraido: "Anafe" },
        { normal: "Cantimplora", distraido: "Botella de agua" }
    ],
    'Paises': [
        { normal: "India", distraido: "Pakistán" },
        { normal: "China", distraido: "Japón" },
        { normal: "Estados Unidos", distraido: "Canadá" },
        { normal: "Indonesia", distraido: "Malasia" },
        { normal: "Pakistán", distraido: "Afganistán" },
        { normal: "Nigeria", distraido: "Níger" },
        { normal: "Brasil", distraido: "Argentina" },
        { normal: "Bangladesh", distraido: "Birmania" },
        { normal: "Rusia", distraido: "Ucrania" },
        { normal: "México", distraido: "Guatemala" },
        { normal: "Etiopía", distraido: "Eritrea" },
        { normal: "Japón", distraido: "Corea del Sur" },
        { normal: "Filipinas", distraido: "Taiwán" },
        { normal: "Egipto", distraido: "Sudán" },
        { normal: "Vietnam", distraido: "Camboya" },
        { normal: "Irán", distraido: "Irak" },
        { normal: "Turquía", distraido: "Grecia" },
        { normal: "Alemania", distraido: "Austria" },
        { normal: "Tailandia", distraido: "Laos" },
        { normal: "Tanzania", distraido: "Kenia" },
        { normal: "Reino Unido", distraido: "Irlanda" },
        { normal: "Francia", distraido: "España" },
        { normal: "Sudáfrica", distraido: "Namibia" },
        { normal: "Italia", distraido: "Suiza" },
        { normal: "Kenia", distraido: "Uganda" },
        { normal: "Colombia", distraido: "Venezuela" },
        { normal: "Corea del Sur", distraido: "Corea del Norte" },
        { normal: "Corea del Norte", distraido: "China" },
        { normal: "España", distraido: "Portugal" },
        { normal: "Uganda", distraido: "Ruanda" },
        { normal: "Argentina", distraido: "Chile" },
        { normal: "Argelia", distraido: "Marruecos" },
        { normal: "Ucrania", distraido: "Polonia" },
        { normal: "Sudán", distraido: "Chad" },
        { normal: "Irak", distraido: "Siria" },
        { normal: "Canadá", distraido: "Alaska" },
        { normal: "Uzbekistán", distraido: "Kazajistán" },
        { normal: "Marruecos", distraido: "Sahara Occidental" },
        { normal: "Afganistán", distraido: "Irán" },
        { normal: "Yemen", distraido: "Omán" },
        { normal: "Perú", distraido: "Bolivia" },
        { normal: "Malasia", distraido: "Singapur" },
        { normal: "Mozambique", distraido: "Zimbabue" },
        { normal: "Ghana", distraido: "Costa de Marfil" },
        { normal: "Angola", distraido: "Zambia" },
        { normal: "Arabia Saudita", distraido: "Emiratos Árabes Unidos" },
        { normal: "Nepal", distraido: "Bután" },
        { normal: "Polonia", distraido: "República Checa" },
        { normal: "Costa de Marfil", distraido: "Liberia" }
    ]
};
