const wordsDB = {
    'Animales': [
        { normal: "Perro", distraido: "Lobo" },
        { normal: "Gato", distraido: "Lince" },
        { normal: "León", distraido: "Tigre" },
        { normal: "Elefante", distraido: "Rinoceronte" },
        { normal: "Jirafa", distraido: "Okapi" },
        { normal: "Cebra", distraido: "Caballo" },
        { normal: "Oso", distraido: "Panda" },
        { normal: "Zorro", distraido: "Coyote" },
        { normal: "Lobo", distraido: "Perro" },
        { normal: "Ciervo", distraido: "Alce" },
        { normal: "Vaca", distraido: "Toro" },
        { normal: "Caballo", distraido: "Poni" },
        { normal: "Cerdo", distraido: "Jabalí" },
        { normal: "Oveja", distraido: "Cabra" },
        { normal: "Gallina", distraido: "Gallo" },
        { normal: "Conejo", distraido: "Liebre" },
        { normal: "Ardilla", distraido: "Hámster" },
        { normal: "Ratón", distraido: "Rata" },
        { normal: "Camello", distraido: "Dromedario" },
        { normal: "Rinoceronte", distraido: "Hipopótamo" },
        { normal: "Koala", distraido: "Perezoso" },
        { normal: "Canguro", distraido: "Wallaby" },
        { normal: "Mono", distraido: "Chimpancé" },
        { normal: "Gorila", distraido: "Orangután" },
        { normal: "Pingüino", distraido: "Pato" },
        { normal: "Foca", distraido: "Morsa" },
        { normal: "Delfín", distraido: "Marsopa" },
        { normal: "Ballena", distraido: "Cachalote" },
        { normal: "Tiburón", distraido: "Barracuda" },
        { normal: "Tortuga", distraido: "Galápago" },
        { normal: "Cocodrilo", distraido: "Caimán" },
        { normal: "Serpiente", distraido: "Culebra" },
        { normal: "Loro", distraido: "Guacamayo" },
        { normal: "Colibrí", distraido: "Picaflor" },
        { normal: "Águila", distraido: "Halcón" },
        { normal: "Hormiga", distraido: "Termita" },
        { normal: "Abeja", distraido: "Avispa" },
        { normal: "Mariposa", distraido: "Polilla" },
        { normal: "Araña", distraido: "Tarántula" },
        { normal: "Grillo", distraido: "Saltamontes" },
        { normal: "Escorpión", distraido: "Alacrán" },
        { normal: "Pulpo", distraido: "Calamar" }
    ],
    'Cine': [
        { normal: "Titanic", distraido: "El Hundimiento" },
        { normal: "Star Wars", distraido: "Star Trek" },
        { normal: "Los Vengadores", distraido: "La Liga de la Justicia" },
        { normal: "E.T.", distraido: "Mi Amigo Mac" },
        { normal: "Jurassic Park", distraido: "Godzilla" },
        { normal: "El Rey León", distraido: "El Libro de la Selva" },
        { normal: "Indiana Jones", distraido: "Tomb Raider" },
        { normal: "Tiburón", distraido: "Piraña" },
        { normal: "El Padrino", distraido: "Caracortada" },
        { normal: "Forrest Gump", distraido: "Benjamin Button" },
        { normal: "Spider-Man", distraido: "Batman" },
        { normal: "El Señor de los Anillos", distraido: "Las Crónicas de Narnia" },
        { normal: "Harry Potter", distraido: "Percy Jackson" },
        { normal: "Toy Story", distraido: "Bichos: Una Aventura en Miniatura" },
        { normal: "Piratas del Caribe", distraido: "La Isla del Tesoro" },
        { normal: "Frozen", distraido: "Moana" },
        { normal: "Rápidos y Furiosos", distraido: "Need for Speed" },
        { normal: "Blade Runner 2049", distraido: "Dune" },
        { normal: "Whiplash", distraido: "La La Land" },
        { normal: "El Lobo de Wall Street", distraido: "La Gran Estafa" },
        { normal: "Proyecto X", distraido: "Supercool" }
    ],
    'Colores': [
        { normal: "Rojo", distraido: "Granate" },
        { normal: "Amarillo", distraido: "Dorado" },
        { normal: "Marrón", distraido: "Beige" },
        { normal: "Verde", distraido: "Esmeralda" },
        { normal: "Azul", distraido: "Turquesa" },
        { normal: "Celeste", distraido: "Cian" },
        { normal: "Violeta", distraido: "Lavanda" },
        { normal: "Rosa", distraido: "Fucsia" },
        { normal: "Blanco", distraido: "Marfil" },
        { normal: "Gris", distraido: "Plata" },
        { normal: "Negro", distraido: "Carbón" },
        { normal: "Naranja", distraido: "Mandarina" }
    ],
    'Comida': [
        { normal: "Asado", distraido: "Parrillada" },
        { normal: "Milanesa", distraido: "Escalope" },
        { normal: "Empanadas", distraido: "Canastitas" },
        { normal: "Locro", distraido: "Guiso" },
        { normal: "Choripán", distraido: "Pancho" },
        { normal: "Pastel de papas", distraido: "Pastel de carne" },
        { normal: "Tallarines", distraido: "Fideos" },
        { normal: "Ñoquis", distraido: "Ravioles" },
        { normal: "Pizza", distraido: "Focaccia" },
        { normal: "Hamburguesa", distraido: "Sándwich" },
        { normal: "Flan", distraido: "Pudín" },
        { normal: "Panqueques", distraido: "Crepes" },
        { normal: "Alfajor", distraido: "Galletita" },
        { normal: "Torta", distraido: "Pastel" },
        { normal: "Helado", distraido: "Sorbete" },
        { normal: "Ensalada de frutas", distraido: "Macedonia" }
    ],
    'Deportes': [
        { normal: "Fútbol", distraido: "Rugby" },
        { normal: "Baloncesto", distraido: "Voleibol" },
        { normal: "Béisbol", distraido: "Críquet" },
        { normal: "Tenis", distraido: "Pádel" },
        { normal: "Golf", distraido: "Mini-golf" },
        { normal: "Natación", distraido: "Waterpolo" },
        { normal: "Atletismo", distraido: "Gimnasia" },
        { normal: "Boxeo", distraido: "Kickboxing" },
        { normal: "Rugby", distraido: "Fútbol Americano" },
        { normal: "Hockey", distraido: "Patinaje" },
        { normal: "Ciclismo", distraido: "Motociclismo" },
        { normal: "Esgrima", distraido: "Kendo" },
        { normal: "Judo", distraido: "Karate" },
        { normal: "Surf", distraido: "Bodyboard" },
        { normal: "Esquí", distraido: "Snowboard" },
        { normal: "Escalada", distraido: "Alpinismo" }
    ],
    'Lol': [
        { normal: "Sócrates", distraido: "Platón" },
        { normal: "Cristóbal Colón", distraido: "Américo Vespucio" },
        { normal: "Monopoly", distraido: "Estanciero" },
        { normal: "Discord", distraido: "Skype" },
        { normal: "Minecraft", distraido: "Roblox" },
        { normal: "Impostor", distraido: "Detective" },
        { normal: "WhatsApp", distraido: "Telegram" },
        { normal: "Gmail", distraido: "Outlook" },
        { normal: "YouTube", distraido: "Vimeo" },
        { normal: "TikTok", distraido: "Instagram Reels" },
        { normal: "Camaro", distraido: "Mustang" },
        { normal: "Batería", distraido: "Pila" },
        { normal: "Nikola Tesla", distraido: "Thomas Edison" },
        { normal: "Insulto", distraido: "Pirope" }
    ],
    'Lugares': [
        { normal: "Aeropuerto", distraido: "Terminal de autobuses" },
        { normal: "Puerto", distraido: "Muelle" },
        { normal: "Fábrica", distraido: "Taller" },
        { normal: "Granja", distraido: "Estancia" },
        { normal: "Bosque", distraido: "Selva" },
        { normal: "Desierto", distraido: "Sábana" },
        { normal: "Volcán", distraido: "Montaña" },
        { normal: "Cementerio", distraido: "Morgue" },
        { normal: "Estadio", distraido: "Coliseo" },
        { normal: "Piscina", distraido: "Alberca" },
        { normal: "Gimnasio", distraido: "Centro deportivo" },
        { normal: "Cine", distraido: "Teatro" },
        { normal: "Biblioteca", distraido: "Librería" },
        { normal: "Museo", distraido: "Galería de arte" },
        { normal: "Supermercado", distraido: "Mercado" },
        { normal: "Hotel", distraido: "Hostal" },
        { normal: "Castillo", distraido: "Fortaleza" },
        { normal: "Cueva", distraido: "Caverna" },
        { normal: "Isla", distraido: "Archipiélago" },
        { normal: "Planeta", distraido: "Estrella" }
    ],
    'Objetos': [
        { normal: "Mesa", distraido: "Escritorio" },
        { normal: "Celular", distraido: "Teléfono fijo" },
        { normal: "Botella", distraido: "Frasco" },
        { normal: "Silla", distraido: "Banqueta" },
        { normal: "Lámpara", distraido: "Foco" },
        { normal: "Televisión", distraido: "Monitor" },
        { normal: "Computadora", distraido: "Laptop" },
        { normal: "Libro", distraido: "Cuaderno" },
        { normal: "Bolígrafo", distraido: "Lápiz" },
        { normal: "Mochila", distraido: "Bolso" },
        { normal: "Zapatos", distraido: "Zapatillas" },
        { normal: "Reloj", distraido: "Cronómetro" },
        { normal: "Vaso", distraido: "Copa" },
        { normal: "Tenedor", distraido: "Trinche" },
        { normal: "Cuchara", distraido: "Cucharón" },
        { normal: "Cuchillo", distraido: "Navaja" },
        { normal: "Cama", distraido: "Catrera" },
        { normal: "Espejo", distraido: "Reflejo" },
        { normal: "Martillo", distraido: "Mazo" },
        { normal: "Guitarra", distraido: "Bajo" },
        { normal: "Piano", distraido: "Teclado" }
    ],
    'Paises': [
        { normal: "India", distraido: "Pakistán" },
        { normal: "China", distraido: "Japón" },
        { normal: "Estados Unidos", distraido: "Canadá" },
        { normal: "Brasil", distraido: "Argentina" },
        { normal: "Rusia", distraido: "Ucrania" },
        { normal: "México", distraido: "Guatemala" },
        { normal: "Alemania", distraido: "Austria" },
        { normal: "Reino Unido", distraido: "Irlanda" },
        { normal: "Francia", distraido: "España" },
        { normal: "Italia", distraido: "Grecia" },
        { normal: "Corea del Sur", distraido: "Corea del Norte" },
        { normal: "España", distraido: "Portugal" },
        { normal: "Argentina", distraido: "Uruguay" },
        { normal: "Canadá", distraido: "Alaska" }
    ]
};